import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1200, height: 900 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:5173', { waitUntil: 'networkidle', timeout: 30000 });
await p.waitForTimeout(3000);
const el = await p.$('.spotlight-projects-desktop');
await el.scrollIntoViewIfNeeded();
await p.waitForTimeout(800);
await el.screenshot({ path: '/tmp/sw_zoom.png' });
await b.close(); console.log('ok');
